eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
spring:
  application:
    name: weather-report
  thymeleaf:
    cache: false
server:
  port: 8084
feign:
  hystrix:
    enabled: true

